ConfigRequestQuestionApp/ConfigRequestQuestionApp/Controllers/BuildsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConfigRequestQuestionApp.Models;
using System.Web.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.Web.Script.Serialization;

namespace ConfigRequestQuestionApp.Controllers
{
    public class BuildsController : Controller
    {
        #region Build Controller Objects

        //Build Controller Objects//
        private List<Build> buildList;
        private Build buildSelected;
        private List<Question> questionList;

        #endregion

        #region Index Action Result

        // GET: Builds
        public ActionResult Index()
        {
            LoadBuilds();
            return View(buildList);
        }

        #endregion

        #region Build Action Result

        public ActionResult Build(int ID)
        {
            buildSelected = new Build();
            LoadBuildByID(ID,0);
            return View(buildSelected);
        }

        #endregion

        #region Manage Builds

        public ActionResult ManageBuild(string type, int bID = 0, int vID = 0)
        {
            if (type == "Edit")
            {
                return View();
            }
            else 
            {
                return View();
            }
        }


        [HttpPost]
        public string BuildDataInitialize(string type, int bID = 0, int vID = 0)
        {
            buildSelected = new Build();
            JavaScriptSerializer buildJson = new JavaScriptSerializer();


            switch (type)
            {
                case "Edit":
                    LoadBuildByID(bID, vID);
                    break;
                default: //New
                    buildSelected.BuildVersionList.Add(new BuildVersion());
                    buildSelected.CurrentBuildName = "New Build..";
                    buildSelected.BuildVersionList[0].VersionNum = 1;
                    buildSelected.BuildVersionList[0].VUpdt = DateTime.Now;
                    buildSelected.BuildVersionList[0].QuestionList.Add(new Question());
                    buildSelected.BuildVersionList[0].QuestionList[0].QOptions.Add(new QuestionOptions());
                    break;
            }            
            
            return buildJson.Serialize(buildSelected);
            //return buildSelected.BuildVersionList.Where(x => x.VersionId == buildSelected.SelectedVersion).FirstOrDefault().BuildTreeJson;
        }

        [HttpPost]
        public string GetAllQuestions()
        {
            LoadQuestions();
            return new JavaScriptSerializer().Serialize(questionList);
        }


        [HttpPost]
        public void PostBuildData(Build buildData)
        {

            Console.WriteLine(buildData);
            return;
        }

        [HttpPost]
        public string SaveQuestion(Question SaveQ, int BuildVersionID)
        {
            SaveQ.Save(BuildVersionID);
            return new JavaScriptSerializer().Serialize(SaveQ);
        }

        #endregion

        #region Load Methods

        private void LoadBuilds()
        {
            Build buildItem = new Build();
            buildList = new List<Build>();

            try
            {
                //Create Connection Properties
                SqlConnection dbCon = new SqlConnection(
                            WebConfigurationManager.ConnectionStrings["amsRulesDB"].ConnectionString
                            );

                //Create Command
                SqlCommand cmd = new SqlCommand("GetBuildList", dbCon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandTimeout = 60;

                //Open Connection
                dbCon.Open();

                //Load into reader
                SqlDataReader dr = cmd.ExecuteReader();


                while (dr.Read())
                {
                    buildItem = new Build();
                    buildItem.BuildID = int.Parse(dr[dr.GetOrdinal("build_id")].ToString());
                    buildItem.CurrentBuildName = dr[dr.GetOrdinal("build_name")].ToString();
                    buildItem.CurrentSolution = dr[dr.GetOrdinal("solution_name")].ToString();
                    buildItem.CurrentSolutionCD = int.Parse(dr[dr.GetOrdinal("solution_cd")].ToString());
                    buildItem.CurrentVersion = int.Parse(dr[dr.GetOrdinal("current_version")].ToString());
                    buildList.Add(buildItem);
                }

                dbCon.Close();

            }
            catch (Exception)
            {
                throw;
            }
        }

        private void LoadBuildByID(int buildID, int versionID)
        {

            try
            {

                //Create Connection Properties
                SqlConnection dbCon = new SqlConnection(
                            WebConfigurationManager.ConnectionStrings["amsRulesDB"].ConnectionString
                            );

                //Create Command
                SqlCommand cmd = new SqlCommand("GetBuildInfoByID", dbCon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandTimeout = 60;
                BuildVersion version;


                //Add Paramaters
                cmd.Parameters.Add("@buildID", SqlDbType.Int).Value = buildID;


                //Open Connection
                dbCon.Open();

                //Load into reader
                SqlDataReader dr = cmd.ExecuteReader();

                while (dr.Read())
                {
                    buildSelected.BuildID = int.Parse(dr[dr.GetOrdinal("build_id")].ToString());
                    buildSelected.CurrentBuildName = dr[dr.GetOrdinal("build_name")].ToString();
                    buildSelected.CurrentSolution = "See Version Info";
                    buildSelected.CurrentSolutionCD = 0; //See Version Info
                    buildSelected.CurrentVersion = int.Parse(dr[dr.GetOrdinal("build_version_id")].ToString());

                    //Load Version Info

                    version = new BuildVersion();

                    version.VersionId = int.Parse(dr[dr.GetOrdinal("build_version_id")].ToString());
                    version.VersionNum = int.Parse(dr[dr.GetOrdinal("version_num")].ToString());
                    version.FirstQID = int.Parse(dr[dr.GetOrdinal("first_q_id")].ToString());
                    version.BuildName = dr[dr.GetOrdinal("build_name")].ToString();
                    version.SolutionCD = int.Parse(dr[dr.GetOrdinal("solution_cd")].ToString());
                    version.Solution = dr[dr.GetOrdinal("solution_name")].ToString();
                    version.VUpdt = dr.GetDateTime(dr.GetOrdinal("updt_dt_tm"));// DateTime.Parse(dr[dr.GetOrdinal("updt_dt_tm")].ToString());
                    version.VUpdtID = int.Parse(dr[dr.GetOrdinal("updt_id")].ToString());
                    version.VUpdtName = dr[dr.GetOrdinal("updt_name")].ToString();

                    buildSelected.BuildVersionList.Add(version);
                }

                dbCon.Close();

                switch (versionID)
                {
                    case 0:
                        //if not specific, just load the current
                        LoadQuestionByVersionID(buildSelected.CurrentVersion);
                        break;
                    default:
                        LoadQuestionByVersionID(versionID);
                        break;
                }
                
            }
            catch (Exception)
            {
                throw;
            }

        }

        private void LoadQuestionByVersionID(int versionID)
        {
            Question qItem;
            buildSelected.SelectedVersion = versionID;

            try
            {
                //Create Connection Properties
                SqlConnection dbCon = new SqlConnection(
                            WebConfigurationManager.ConnectionStrings["amsRulesDB"].ConnectionString
                            );

                //Create Command
                SqlCommand cmd = new SqlCommand("GetBuildQuestionsByVersionID", dbCon);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandTimeout = 60;

                //Add Paramaters
                cmd.Parameters.Add("@versionID", SqlDbType.Int).Value = versionID;


                //Open Connection
                dbCon.Open();

                //Load into reader
                SqlDataReader dr = cmd.ExecuteReader();

                //Other Variables
                int questionID = 0;
                //Build Version Object
                BuildVersion loadVersion = buildSelected.BuildVersionList.Where(x => x.VersionId == versionID).FirstOrDefault();

                while (dr.Read())
                {
                    qItem = new Question();

                    questionID = int.Parse(dr[dr.GetOrdinal("question_id")].ToString());

                    //If question already exists, it must be for options
                    if (loadVersion.QuestionList.Any(x => x.QuestionID == questionID))
                    {
                            QuestionOptions qOpt = new QuestionOptions();
                            qOpt.QuestionID = questionID;
                            qOpt.QOptID = int.Parse(dr[dr.GetOrdinal("q_opt_id")].ToString());
                            qOpt.LabelText = dr[dr.GetOrdinal("q_opt_label")].ToString();
                            qOpt.ChildID = int.Parse(dr[dr.GetOrdinal("child_q_id")].ToString());
                            qOpt.Sequence = int.Parse(dr[dr.GetOrdinal("seq")].ToString());

                            loadVersion.QuestionList.Where(x => x.QuestionID == questionID).FirstOrDefault().QOptions.Add(qOpt);
                            loadVersion.QuestionList.Where(x => x.QuestionID == questionID).FirstOrDefault().ReSequenceOptions();
                    }
                    else
                    {//New question

ConfigRequestQuestionApp/ConfigRequestQuestionApp/Views/Shared/FailWhale.cshtml
@{
    ViewBag.Title = "Error";
}


<h2>404: Page Not Found</h2>
@if (@Request.Params["aspxerrorpath"] != null)
{
    <p>URL you are trying to navigate to is invalid. <strong>'@Request.Params["aspxerrorpath"]' </strong>Please check the URL, and try again.</p>
}
else
{
    <p>URL you hare trying to navigate to is invalid or has been moved. <strong>'@Request.Url'</strong> Please review the URL and make any necessary changes. </p>


    
}

ConfigRequestQuestionApp/ConfigRequestQuestionApp/Views/Shared/_LayoutAssociate.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

ConfigRequestQuestionApp/ConfigRequestQuestionApp/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CRQApp</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <header class="global-head">
        <div class="container-fullwidth global-head-inner">
            <div id="header-row" class="row align-items-center">
                <div class="col-2">
                    <img class="global-logo" src="//webcdn.cerner.com/Content/Images/cernerLogo_FC_T.png" alt="Cerner Logo" />
                </div>
                <div id="inspire-quote" class="col-3">
                    <span class="font-italic">
                        "Healthcare is too important to stay the same."
                    </span>
                </div>
                <div class="col-7 user-info">
                    <div class="row">
                        <div class="col-8" align="center">
                            @*Placeholder for notifications.*@
                        </div>
                        <div class="col-4" align="right">
                            <div class="btn-group">
                                <button id="global-user-dropdown" type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img id="user-img" src="https://assets3.thrillist.com/v1/image/2547068/size/tmg-article_tall;jpeg_quality=20.jpg" class="img-thumbnail rounded-circle" />
                                    <span id="user-name">Dalton Sherley</span>
                                </button>
                                <div class="dropdown-menu global-user-dropdown-menu">
                                    <a class="dropdown-item" href="#">My Requests</a>
                                    <a class="dropdown-item" href="#">Settings</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <nav id="global-nav" class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item dropdown position-static">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        My Requests
                    </a>
                    <div class="dropdown-menu w-100" aria-labelledby="navbarDropdown">
                        <div class="row">
                            <div class="col-5">
                                <span class="font-weight-bold nav-drop-head-item">Requests</span>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">All Requests</a>
                                <a class="dropdown-item" href="#">Open Requests</a>
                                <a class="dropdown-item" href="#">Closed Requests</a>
                            </div>
                            <div class="col-5">
                                <span class="font-weight-bold nav-drop-head-item">Recent Requests</span>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">SR 12345 - New XYZ Project</a>
                                <a class="dropdown-item" href="#">SR 67891 - New ABC Project</a>
                                <a class="dropdown-item" href="#">SR 15975 - New RTY Project</a>
                            </div>
                            <div class="col-2">
                                <div class="row h-100 align-items-center">
                                    <div class="col-12" align="center">
                                        <button id="new-request-btn" class="btn btn-primary" onclick="window.location.href='/Builds'">New Request</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <a id="manage-builds" class="nav-link" href="@Url.Action("ManageBuild","Builds", new {type="Edit",bID="1"})">Manage Builds</a>@*"/Builds/ManageBuild/Edit?BID=1&VID=1"*@
                </li>
                <li class="nav-item">
                    <a id="new-build" class="nav-link" href="@Url.Action("ManageBuild","Builds", new {type="New"})">New Build</a>@*"/Builds/ManageBuild/Edit?BID=1&VID=1"*@
                </li>
            </ul>
        </nav>

    </header>



    @*<nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Cerner Config Request</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Builds">Builds</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                </ul>
            </div>
        </nav>*@


    <div id="main-container" class="container-fullwidth body-content">
        @RenderBody()
    </div>


    <footer id="global-footer" class="footer">
        <div class="container-fullwidth">
            <div class="row">
                <div class="col-3">

                </div>
                <div class="col-6" align="center">
                    <span class="text-muted">&copy; @DateTime.Now.Year - ConfigRequestQuestionApp</span>
                </div>
                <div class="col-3">

                </div>

            </div>

        </div>
    </footer>


    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custscripts")
    @RenderSection("Scripts", false/*required*/)
    <!-- flatpickr -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_blue.css">

    <!-- Main Quill library -->
    <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <!-- Theme included stylesheets -->
    <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
   
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    @*<footer>
            <hr />
            <p>&copy; @DateTime.Now.Year - ConfigRequestQuestionApp</p>
        </footer>*@
</body>
</html>